### ISSUE TITLE
datatype support

### ISSUE THREAD

**Issue by JMensch** [OpenDataPhillyAPI/bike_racks#1]
@blindman how many of these return types are you thinking we should support? https://www.opendataphilly.org/dataset/bike-rack-locations-in-philadelphia

**Comment by blindman** [comment]
So, I'm assuming I should have read this one before #2...

I would say focus on CSV and API since that is the core of data.  Anything beyond that would be an improvement (unless you think otherwise).  In my eyes, I see supporting only as much to create a complete set of data where the CSV might contain historical rentals per location and the API would not include that so it would be a feature to include that.
